version: '3.9'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '${REDIS_PORT:-6379}'
    volumes:
      - './redis-data:/data'
    networks:
      - bullmq
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
networks:
  bullmq:
    driver: bridge

